### ISSUE TITLE
Remove common directory

### ISSUE THREAD

**Issue by dentonmwood** [calebdehaan/codeDuplicationParser#55]
We should elevate the folders within common to the parent directory and remove the common folder - it's an unnecessary abstraction

**Comment by natiiix** [comment]
@dentonmwood Please close these via the `Close calebdehaan#IssueNumber` directive in the last commit message / PR description body

**Comment by natiiix** [comment]
Solved by 02a2ed8f74f70cdda68b66f3cc2582473c6d267b
