### ISSUE TITLE
Write some actual tests

### ISSUE THREAD

**Issue by natiiix** [calebdehaan/codeDuplicationParser#72]
#### I'd personally suggest [pytest](https://github.com/pytest-dev/pytest), so if no one finds anything better, we could probably use that. It should be relatively easy to use, flexible and very easy to install by a single `pip install` command.

----

For now, it would be enough to just check that parsing modules from the included test repositories doesn't return empty lists or raise any exceptions.

**Comment by dentonmwood** [comment]
`pytest` is currently built into our software (see the `test` directory). This issue is in progress.

**Comment by natiiix** [comment]
@dentonmwood I'm not sure what you mean. The `/test/` directory is an empty module from what I can tell.
