### ISSUE TITLE
Please use argparse library instead of trying to parse CLI arguments manually

### ISSUE THREAD

**Issue by tisnik** [calebdehaan/codeDuplicationParser#81]
https://github.com/calebdehaan/codeDuplicationParser/blob/9abbe0cc7be34234720762588f3fdf38264330f7/code_duplication/src/preprocessing/args_handler.py#L18

See https://github.com/fabric8-analytics/fabric8-analytics-common/blob/master/dashboard/src/cliargs.py for an example

**Comment by natiiix** [comment]
We should definitely do that for consistency with other apps, but it didn't seem like a very high priority for now. It will also make it significantly easier to parse more arguments (various parameters for the algorithms) when we add them to the CLI.
