### ISSUE TITLE
Comparator vs comparer

### ISSUE THREAD

**Issue by tisnik** [calebdehaan/codeDuplicationParser#83]
https://github.com/calebdehaan/codeDuplicationParser/blob/9abbe0cc7be34234720762588f3fdf38264330f7/code_duplication/src/secondary_algorithm/comparer.py#L1

well I'm not native speaker but... should not it be `comparator` and not `comparer` :)

**Comment by natiiix** [comment]
Yes, that's right, but thankfully it will be called "the Chlorine algorithm" instead once #80 is approved. It was just a placeholder name.
